# Generated by Django 4.1.4 on 2022-12-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateTimeField(null=True)),
                ('mood', models.CharField(max_length=25, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
