# Generated by Django 4.1.4 on 2022-12-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patronus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soundscape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meditation_sounds', models.FileField(upload_to='med_sounds/')),
                ('start_and_stop_sounds', models.FileField(upload_to='start_stop_sounds')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_meditation', models.DateTimeField(auto_now_add=True)),
                ('mood_before_meditation', models.CharField(max_length=25, null=True)),
                ('mood_after_mediation', models.CharField(max_length=25, null=True)),
                ('meditation_duratoin', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='meditation.patronus')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
