# Generated by Django 4.1.4 on 2022-12-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0003_patronus_password_alter_userhistory_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopStartSounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_and_stop_sounds', models.FileField(upload_to='start_stop_sounds')),
            ],
        ),
        migrations.RemoveField(
            model_name='soundscape',
            name='start_and_stop_sounds',
        ),
    ]
