# Generated by Django 4.1.4 on 2022-12-16 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0004_stopstartsounds_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soundscape',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='soundscape',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundscape',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='soundscape',
            name='name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundscape',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soundscape',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stopstartsounds',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='soundscape',
            index_together={('id', 'slug')},
        ),
    ]
