# Generated by Django 4.1.4 on 2022-12-23 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0009_usersession_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='name',
            new_name='song_name',
        ),
    ]
