# Generated by Django 4.1.4 on 2022-12-24 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0012_alter_usersession_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patronus',
        ),
    ]
