# Generated by Django 4.1.4 on 2022-12-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0013_delete_patronus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='category',
        ),
        migrations.AddField(
            model_name='mood',
            name='category',
            field=models.ManyToManyField(to='meditation.category'),
        ),
    ]
