# Generated by Django 4.1.4 on 2022-12-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0015_remove_mood_category_category_moods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='moods',
        ),
        migrations.AddField(
            model_name='mood',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='meditation.category'),
            preserve_default=False,
        ),
    ]
